### ISSUE TITLE
Read a promotion

### ISSUE THREAD

**Issue by ChungLinWu0829** [CSCI-GA-2820-SU24-001/promotions#1]
As a Promotion Manager
I need the ability to read a promotion
So that I can find details of specific promotion id

Assumptions:

- We will store the promotion details in a PostgreSQL database
- An promotion has an id, product id, duration and deals on products, such as sale, buy 1 get 1 free, 20% off

Acceptance Criteria:

Given there is at least one promotion in the database
When I read a promotion with its id
Then there should be displayed the detail of the promotion

**Comment by hrithik2200** [comment]
There should also be a time duration column for reading the resource (example: sale for one week, etc)
