### ISSUE TITLE
Create UI function to Query and List Promotions (Table)

### ISSUE THREAD

**Issue by anirudh28** [CSCI-GA-2820-SU24-001/promotions#40]
**As a**  promotion manager 
 **I need**  to query and list all promotions
 **So that** I can find promotions which match some criteria in the UI
   
 ### Details and Assumptions
 * Should include separate boxes for query paramters
 * Seach should send a GET request to the backend
 * Retrieved promotions should be displayed in table form below
   
 ### Acceptance Criteria  
   
 ```gherkin
Given a running UI
When I enter some query parameters for a specific promotion date, scope or type into the form
When I click on Search
I should see a list of promotions which conform to those query parameters
 ```

**Comment by anirudh28** [comment]
**As a**  developer 
 **I need**  to create UI for the promotions
 **So that** the promotions can be viewed and edited from the UI
   
 ### Details and Assumptions
 * View all the Promtions 
 * Create a Promotion
 * Update a Promotion
 * Delete a Promotion
   
 ### Acceptance Criteria  
   
 ```gherkin
Make an interactive UI for viewing, creating and updating promotions.
 ```

**Comment by mingyi850** [comment]
When the page loads, just call Get all promotions and display the table of all promotions on the UI.
