### ISSUE TITLE
Update Functionality of the UI Page

### ISSUE THREAD

**Issue by anirudh28** [CSCI-GA-2820-SU24-001/promotions#44]

**Comment by anirudh28** [comment]
**As a**  developer 
 **I need**  to build the update functionality on the UI Page
 **So that** the promotions can be updated from the UI Page
   
 ### Details and Assumptions
 * Update tab will allow user to update existing Promotions 
   
 ### Acceptance Criteria  
   
 ```gherkin
When I request to update the promotions from the UI
Then I can update the promotion and see the result on the UI
 ```

**Comment by mingyi850** [comment]
Update button should be on the Promotion Details page.
It should open a modal to update fields which can be updated (not accounting fields)
